### ISSUE TITLE
How to setup in Kaggle notebook?

### ISSUE THREAD

**Issue by dsbyprateekg** [Deci-AI/super-gradients#1022]
### Describe the bug
I am trying to install the required libraries in a kaggle notebook:

- !pip install super-gradients==3.1.0
- !pip install imutils
- !pip install roboflow
- !pip install pytube --upgrade
- !pip install torchinfo

After installing when I import the module using `from super_gradients.training import models` , I am facing error `OSError: /opt/conda/lib/python3.10/site-packages/nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11`

Please find attached log file of pip install.
[yolo-nas-installation-logs.txt](https://github.com/Deci-AI/super-gradients/files/11487971/yolo-nas-installation-logs.txt)

**Comment by Louis-Dupont** [comment]
Hi, this is an issue due to PyTorch and not SuperGradients
You can check these:
- https://github.com/hpcaitech/ColossalAI/issues/2901
- https://stackoverflow.com/questions/74394695/how-does-one-fix-when-torch-cant-find-cuda-error-version-libcublaslt-so-11-no

**Comment by BloodAxe** [comment]
Try installing (restart the kernel beforehead) the latest nightly version of SG that lifts up pytorch requirements, so it will use what is already installed on kaggle. I believe this should resolve the issue:
`pip install -U git+https://github.com/Deci-AI/super-gradients.git`

**Comment by dsbyprateekg** [comment]
> Try installing (restart the kernel beforehead) the latest nightly version of SG that lifts up pytorch requirements, so it will use what is already installed on kaggle. I believe this should resolve the issue: `pip install -U git+https://github.com/Deci-AI/super-gradients.git`

Thanks @BloodAxe ! it resolved the issue.
