### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by adamekcerv** [Deci-AI/super-gradients#1035]
### 💡 Your Question

Hi,
I have tried to fine tune model with my dataset by when I try to train a model:

`trainer.train(model=model, 
                  training_params=train_params, 
                  train_loader=train_data, 
                  valid_loader=val_data)`

I am getting this error:

`OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 0 has a total capacty of 11.00 GiB of which 0 bytes is free. Of the allocated memory 10.22 GiB is allocated by PyTorch, and 115.42 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I have tried to reduce a batch size to 1 and also torch.cuda.empty_cache().
Version of my torch is '2.1.0.dev20230517+cu121' and CUDA is 12.1. And I am running on gtx 1080ti. Memory is not full on task manager.

What Can I do?

**Comment by BloodAxe** [comment]
It would be easier to help you if you provide more context:
What model you are trying to train?
Is it notebook or regular python script?
What is dataset and image size in particular that you are training on?

**Comment by adamekcerv** [comment]
> It would be easier to help you if you provide more context:
> What model you are trying to train?
> Is it notebook or regular python script?
> What is dataset and image size in particular that you are training on?

I am training yolo_nas_l on Jupyter notebook. I am training on this test dataset:

from roboflow import Roboflow
rf = Roboflow(api_key="<your-roboflow-key-here>")
project = rf.workspace("atathamuscoinsdataset").project("u.s.-coins-dataset-a.tatham")
dataset = project.version(5).download("yolov5")

**Comment by BloodAxe** [comment]
Try with smaller model, YoloNAS-L is pretty big. We had good experience with fine-tuning S & L models on 16Gb Colab instances. It might be that 11Gb on 1080 is just not enough for training in 640x640 resolution.

**Comment by htmtmx** [comment]
Hello @adamekcerv , I had the same problem, and I solved it by reducing the batch_size, taking into account numbers that are powers of 2. In my case, the batch_size was set to 16, but reducing it to 8 eliminated the out of memory error.

Here more info: [Batch size in DeepLearning](https://keepcoding.io/blog/batch-size-deep-learning/)

**Comment by Halafz7** [comment]
Hi @htmtmx , may I know what file that allow to change the batch_size? I've been searched for some times but still can't find it. Thankyou

**Comment by htmtmx** [comment]
> Hi @htmtmx , may I know what file that allow to change the batch_size? I've been searched for some times but still can't find it. Thankyou

@Halafz7 it depends about what feature you are using, in my case I've been working with clasification notebook and I've change batch_size in training_params

**Comment by Halafz7** [comment]
> > Hi @htmtmx , may I know what file that allow to change the batch_size? I've been searched for some times but still can't find it. Thankyou
> 
> @Halafz7 it depends about what feature you are using, in my case I've been working with clasification notebook and I've change batch_size in training_params

I also using classification notebook. What file name? Did you just add the batch_size in the training_params? Since I didn't find the batch_size options in default_train_params.yaml file

**Comment by htmtmx** [comment]
@Halafz7 just go to the cell in the notebook where `trainig_params` are defined and change the `batch_size` with the key value like a `training_params['batch_size'] = your_batch_size_value`, there's no a file, just a cell in the step training setup

**Comment by Halafz7** [comment]
> @Halafz7 just go to the cell in the notebook where `trainig_params` are defined and change the `batch_size` with the key value like a `training_params['batch_size'] = your_batch_size_value`, there's no a file, just a cell in the step training setup
> 
> I hope this can be useful

I've changed the value of batch_size in the cell just like u told me before (from default=256 to 128) :
![image](https://github.com/Deci-AI/super-gradients/assets/79700580/b50ca0d4-2272-4a40-86fb-60af238f902c)

But when the training started, it shows the default
![image](https://github.com/Deci-AI/super-gradients/assets/79700580/fb1db98c-adbc-429d-a71d-d8697c8e7b5e)

Can you mention what's wrong with my command? Thank you

**Comment by BloodAxe** [comment]
A `training_params` is not a right place to change the batch size.
Look how you instantiate `train_data`. 
1) If you are creating DataLoader manually then you pass the value as follows: `train_data = DataLoader(..., batch_size)`

2) If you are instantiating DataLoader using SG `dataloaders.get` then you can pass it via `dataloaders.get(.., dataloader_params=dict(batch_size=YOUR_VALUE))`

3) If you are using YAML configs, then key setting you want to change is under `dataset_param.val_dataloader_params.batch_size`.

**Comment by Halafz7** [comment]
> A `training_params` is not a right place to change the batch size. Look how you instantiate `train_data`.
> 
> 1. If you are creating DataLoader manually then you pass the value as follows: `train_data = DataLoader(..., batch_size)`
> 2. If you are instantiating DataLoader using SG `dataloaders.get` then you can pass it via `dataloaders.get(.., dataloader_params=dict(batch_size=YOUR_VALUE))`
> 3. If you are using YAML configs, then key setting you want to change is under `dataset_param.val_dataloader_params.batch_size`.

Hi @BloodAxe , the second one works for me, thanks a lot!
