### ISSUE TITLE
Train a yolo nas model on custom coco datasets

### ISSUE THREAD

**Issue by mark1ng123** [Deci-AI/super-gradients#1105]
Hey, 
I was able to train on a custom coco data-set when he had only one class, i received good results, i was using the coco2017train and val data loaders and the recipes that are found in this library to train coco with your proven hyper-parameters and data-set parameters, 
When i tried to train on more then one class i wasn't able to run my training process i received:
```
Train epoch 0:   0%|          | 0/31 [00:00<?, ?it/s]../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [65,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [66,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [72,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [73,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [74,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [75,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [76,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [77,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [78,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [80,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [81,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [82,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [83,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [84,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [85,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [86,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [87,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [88,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [89,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [90,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [91,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [56,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Train epoch 0:   0%|          | 0/31 [00:04<?, ?it/s]
[2023-05-31 10:15:11] INFO - base_sg_logger.py - [CLEANUP] - Successfully stopped system monitoring process
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[12], line 1
----> 1 manager.train()

File ~/picko_gym/PickoGymManager.py:80, in PickoGymManager.train(self, use_pretrained)
     78 else:
     79     model = self.create_model_object(self.cfg.model_name, self.cfg.num_classes, pretrained=False, checkpoint=self.cfg.checkpoint)
---> 80 self.trainer.train(model=model,
     81               training_params=self.cfg.train_params['train_params'],
     82               train_loader=self.cfg.train_loader,
     83               valid_loader=self.cfg.val_loader)

File ~/.local/lib/python3.8/site-packages/super_gradients/training/sg_trainer/sg_trainer.py:1240, in Trainer.train(self, model, training_params, train_loader, valid_loader, additional_configs_to_log)
   1233 if (
   1234     device_config.multi_gpu == MultiGPUMode.DISTRIBUTED_DATA_PARALLEL
   1235     and hasattr(self.train_loader, "sampler")
   1236     and hasattr(self.train_loader.sampler, "set_epoch")
   1237 ):
   1238     self.train_loader.sampler.set_epoch(epoch)
-> 1240 train_metrics_tuple = self._train_epoch(epoch=epoch, silent_mode=silent_mode)
   1242 # Phase.TRAIN_EPOCH_END
   1243 # RUN PHASE CALLBACKS
   1244 train_metrics_dict = get_metrics_dict(train_metrics_tuple, self.train_metrics, self.loss_logging_items_names)

File ~/.local/lib/python3.8/site-packages/super_gradients/training/sg_trainer/sg_trainer.py:441, in Trainer._train_epoch(self, epoch, silent_mode)
    438     outputs = self.net(inputs)
    440     # COMPUTE THE LOSS FOR BACK PROP + EXTRA METRICS COMPUTED DURING THE LOSS FORWARD PASS
--> 441     loss, loss_log_items = self._get_losses(outputs, targets)
    443 context.update_context(preds=outputs, loss_log_items=loss_log_items)
    444 self.phase_callback_handler.on_train_batch_loss_end(context)

File ~/.local/lib/python3.8/site-packages/super_gradients/training/sg_trainer/sg_trainer.py:474, in Trainer._get_losses(self, outputs, targets)
    472 def _get_losses(self, outputs: torch.Tensor, targets: torch.Tensor) -> Tuple[torch.Tensor, tuple]:
    473     # GET THE OUTPUT OF THE LOSS FUNCTION
--> 474     loss = self.criterion(outputs, targets)
    475     if isinstance(loss, tuple):
    476         loss, loss_logging_items = loss

File ~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs)
   1190 # If we don't have any hooks, we want to skip the rest of the logic in
   1191 # this function, and just call forward.
   1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194     return forward_call(*input, **kwargs)
   1195 # Do not call functions when jit is used
   1196 full_backward_hooks, non_full_backward_hooks = [], []

File ~/.local/lib/python3.8/site-packages/super_gradients/training/losses/ppyolo_loss.py:774, in PPYoloELoss.forward(self, outputs, targets)
    772     alpha_l = 0.25
    773 else:
--> 774     assigned_labels, assigned_bboxes, assigned_scores = self.assigner(
    775         pred_scores=pred_scores.detach().sigmoid(),  # Pred scores are logits on training for numerical stability
    776         pred_bboxes=pred_bboxes.detach() * stride_tensor,
    777         anchor_points=anchor_points,
    778         num_anchors_list=num_anchors_list,
    779         gt_labels=gt_labels,
    780         gt_bboxes=gt_bboxes,
    781         pad_gt_mask=pad_gt_mask,
    782         bg_index=self.num_classes,
    783     )
    784     alpha_l = -1
    785 # rescale bbox

File ~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs)
   1190 # If we don't have any hooks, we want to skip the rest of the logic in
   1191 # this function, and just call forward.
   1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194     return forward_call(*input, **kwargs)
   1195 # Do not call functions when jit is used
   1196 full_backward_hooks, non_full_backward_hooks = [], []

File ~/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File ~/.local/lib/python3.8/site-packages/super_gradients/training/losses/ppyolo_loss.py:513, in TaskAlignedAssigner.forward(self, pred_scores, pred_bboxes, anchor_points, num_anchors_list, gt_labels, gt_bboxes, pad_gt_mask, bg_index, gt_scores)
    510 alignment_metrics = bbox_cls_scores.pow(self.alpha) * ious.pow(self.beta)
    512 # check the positive sample's center in gt, [B, n, L]
--> 513 is_in_gts = check_points_inside_bboxes(anchor_points, gt_bboxes)
    515 # select topk largest alignment metrics pred bbox as candidates
    516 # for each gt, [B, n, L]
    517 is_in_topk = gather_topk_anchors(alignment_metrics * is_in_gts, self.topk, topk_mask=pad_gt_mask)

File ~/.local/lib/python3.8/site-packages/super_gradients/training/losses/ppyolo_loss.py:197, in check_points_inside_bboxes(points, bboxes, center_radius_tensor, eps)
    195 right = xmax - x
    196 bottom = ymax - y
--> 197 delta_ltrb = torch.cat([left, top, right, bottom], dim=-1)
    198 is_in_bboxes = delta_ltrb.min(dim=-1).values > eps
    199 if center_radius_tensor is not None:
    200     # check whether `points` is in `center_radius`

RuntimeError: CUDA error: device-side assert triggered

``` 
I Modified the number of classes before training, i also gave an all_classes_list as suggested in the documentation of your source code for the CocoDetectionDataset,
Iv'e tried many other options before coming here asking for help, ive tried to change the labels to only 2D BBOX without seg, 
changing the names of the labels, using len(classes)-1 or +1 but none of this tricks worked, 
the labels are well annotated and specified.
Thanks in advance,
Mark

**Comment by shaydeci** [comment]
hey @mark1ng123 , looks to me like there might be wrong number of clases for the criterion or the network.
Can you share your code?

**Comment by mark1ng123** [comment]
@shaydeci Yeah sure, sorry in advance alot of code
This is my training function:
```
@classmethod
    def train(self, use_pretrained: bool = True) -> None:
        """
        :param use_pretrained: Whether or not use a pretrained coco weights
        """
        if use_pretrained:
            model = self.create_model_object(model_name=self.cfg.model_name, checkpoint=self.cfg.checkpoint, exp=self.cfg.experiment)
        else:
            model = self.create_model_object(self.cfg.model_name, self.cfg.num_classes, pretrained=False, checkpoint=self.cfg.checkpoint)
        self.trainer.train(model=model,
                      training_params=self.cfg.train_params['train_params'],
                      train_loader=self.cfg.train_loader,
                      valid_loader=self.cfg.val_loader)
```
Thats how i load the params:
```
def set_dataset_params(self) -> None:
        with open(os.path.join(self.val_data_dir, "dataset_params.yaml"), "r") as val_dataset_params:
                self.val_ds_params = yaml.safe_load(val_dataset_params)
        self.val_ds_params['val_dataset_params']['data_dir'] = self.val_data_dir
        self.val_ds_params['val_dataset_params']['subdir'] = os.path.join(self.val_data_dir, "images")
        self.val_ds_params['val_dataset_params']['json_file'] = "test.json"
        self.val_ds_params['val_dataset_params']['all_classes_list'] = ["BeraleBarila", "ClickBrownWhite", "PurpleSpong", "RedSpong", "SealTape", "Sheka", "SpongeCase", "Tuna", "YellowSpong"]
        if self.train_data_dir != "None":
            with open(os.path.join(self.train_data_dir, "dataset_params.yaml"), "r") as train_dataset_params:
                train_ds_params = yaml.safe_load(train_dataset_params)
                train_ds_params['dataset_params']['data_dir'] = self.train_data_dir
                train_ds_params['dataset_params']['subdir'] = os.path.join(self.train_data_dir, "images")
                train_ds_params['dataset_params']['json_file'] = "train.json"
                train_ds_params['dataset_params']['all_classes_list'] = ["BeraleBarila", "ClickBrownWhite", "PurpleSpong", "RedSpong", "SealTape", "Sheka", "SpongeCase", "Tuna", "YellowSpong"]
            train_dataset_params.close()
            self.ds_params = {**self.val_ds_params ,**train_ds_params}
        val_dataset_params.close()
        
def set_training_params(self) -> None:
        with open(os.path.join(self.train_data_dir, "training_params.yaml"), "r") as training_params:
            loader = yaml.SafeLoader
            loader.add_implicit_resolver(u'tag:yaml.org,2002:float',
                                        re.compile(u'''^(?:
                                        [-+]?(?:[0-9][0-9_]*)\\.[0-9_]*(?:[eE][-+]?[0-9]+)?
                                        |[-+]?(?:[0-9][0-9_]*)(?:[eE][-+]?[0-9]+)
                                        |\\.[0-9_]+(?:[eE][-+][0-9]+)?
                                        |[-+]?[0-9][0-9_]*(?::[0-5]?[0-9])+\\.[0-9_]*
                                        |[-+]?\\.(?:inf|Inf|INF)
                                        |\\.(?:nan|NaN|NAN))$''', re.X),
                                        list(u'-+0123456789.'))
            self.train_params = yaml.load(training_params, loader)
            train_params_copy = self.train_params
            # No get __item__ from ppyoloelost cant define inside
            reg_max = train_params_copy['train_params']['loss']['reg_max']
            user_static_assigner = train_params_copy['train_params']['loss']['use_static_assigner']
            self.num_classes = self.train_params['train_params']['loss']['num_classes']
            self.train_params['train_params']['loss'] = PPYoloELoss(use_static_assigner=user_static_assigner,
                                                         num_classes=self.num_classes,
                                                         reg_max=reg_max)

            self.train_params['train_params']['valid_metrics_list'] = [DetectionMetrics_050(score_thres=train_params_copy['train_params']['valid_metrics_list']['score_thres'],
                                                                                       top_k_predictions=train_params_copy['train_params']['valid_metrics_list']['top_k_predictions'],
                                                                                       num_cls=self.num_classes,
                                                                                       normalize_targets=train_params_copy['train_params']['valid_metrics_list']['normalize_targets'],
                                                                                       post_prediction_callback=PPYoloEPostPredictionCallback(score_threshold=train_params_copy['train_params']['valid_metrics_list']['score_threshold'],
                                                                                                                                              nms_top_k=train_params_copy['train_params']['valid_metrics_list']['nms_top_k'],
                                                                                                                                              max_predictions=train_params_copy['train_params']['valid_metrics_list']['max_predictions'],
                                                                                                                                              nms_threshold=train_params_copy['train_params']['valid_metrics_list']['nms_threshold']))]
        training_params.close()                                                                                                                                              
        print(self.train_params)

    def create_data_loader(self) -> tuple([DataLoader, DataLoader]):
        train_loader = None
        val_loader = None
        if not self.is_classification:
            if self.train_data_dir != "None":
                train_loader = dataloaders.get(name="coco2017_train",
                                            dataset_params=self.ds_params['dataset_params'],
                                            dataloader_params=self.ds_params['dataloader_params'])
            val_loader = dataloaders.get(name="coco2017_val",
                                        dataset_params=self.val_ds_params['val_dataset_params'],
                                        dataloader_params=self.val_ds_params['val_dataloader_params'])
            return train_loader, val_loader 
```
And this are the recepies:
```
train_params:
  average_best_models: True
  warmup_mode: "linear_epoch_step"
  warmup_initial_lr: 1e-6
  lr_warmup_epochs: 3
  initial_lr: 5e-4
  lr_mode": "cosine"
  cosine_final_lr_ratio: 0.1
  optimizer: "Adam"
  optimizer_params:
    weight_decay: 0.0001
  zero_weight_decay_on_bias_and_bn: True
  ema: True
  ema_params: 
    decay: 0.9
    decay_type: "threshold"
    # ONLY TRAINING FOR 10 EPOCHS FOR THIS EXAMPLE NOTEBOOK
  max_epochs: 30
  mixed_precision: True
  loss: 
    use_static_assigner: False
    num_classes: 9
    reg_max: 16
  valid_metrics_list:
    score_thres: 0.1
    top_k_predictions: 300
    num_cls: 9
    normalize_targets: True
    score_threshold: 0.01
    nms_top_k: 1000
    max_predictions: 300
    nms_threshold: 0.7
  metric_to_watch: 'mAP@0.50'
```
```
dataset_params:
  data_dir: /data/coco # root path to coco data
  subdir: images/train2017 # sub directory path of data_dir containing the train data.
  json_file: instances_train2017.json # path to coco train json file, data_dir/annotations/train_json_file.
  input_dim: [250,250]
  cache_dir:
  cache: False
  transforms:
    - DetectionMosaic:
        input_dim: [250,250]
        prob: 1
    - DetectionRandomAffine:
        degrees: 10                  # rotation degrees, randomly sampled from [-degrees, degrees]
        translate: 0.1                # image translation fraction
        scales: [ 0.1, 1.4]              # random rescale range (keeps size by padding/cropping) after mosaic transform.
        shear: 2.0                    # shear degrees, randomly sampled from [-degrees, degrees]
        target_size: [250,250]
        filter_box_candidates: True   # whether to filter out transformed bboxes by edge size, area ratio, and aspect ratio.
        wh_thr: 2                     # edge size threshold when filter_box_candidates = True (pixels)
        area_thr: 0.1                 # threshold for area ratio between original image and the transformed one, when when filter_box_candidates = True
        ar_thr: 20                    # aspect ratio threshold when filter_box_candidates = True
    - DetectionMixup:
        input_dim: [250,250]
        mixup_scale: [ 0.5, 1.5 ]         # random rescale range for the additional sample in mixup
        prob: 1.0                       # probability to apply per-sample mixup
        flip_prob: 0.5                  # probability to apply horizontal flip
    - DetectionHSV:
        prob: 1.0                       # probability to apply HSV transform
        hgain: 5                        # HSV transform hue gain (randomly sampled from [-hgain, hgain])
        sgain: 30                       # HSV transform saturation gain (randomly sampled from [-sgain, sgain])
        vgain: 30                       # HSV transform value gain (randomly sampled from [-vgain, vgain])
    - DetectionHorizontalFlip:
        prob: 0.5                       # probability to apply horizontal flip
    - DetectionPaddedRescale:
        input_dim: [250,250]
        max_targets: 120
    - DetectionTargetsFormatTransform:
        input_dim: [250,250]
        output_format: LABEL_XYWH
  tight_box_rotation: False
  class_inclusion_list:
  max_num_samples: 1000
  with_crowd: False

dataloader_params:
  shuffle: True
  batch_size: 32
  num_workers: 8
  drop_last: True
  pin_memory: True

val_dataset_params:
  data_dir: /data/coco # root path to coco data
  subdir: images/val2017 # sub directory path of data_dir containing the train data.
  json_file: instances_val2017.json # path to coco train json file, data_dir/annotations/train_json_file.
  input_dim: [250, 250]
  cache: False
  transforms:
  - DetectionPaddedRescale:
      input_dim: [250,250]
  - DetectionTargetsFormatTransform:
      max_targets: 50
      input_dim: [250,250]
      output_format: LABEL_CXCYWH
  tight_box_rotation: False
  class_inclusion_list: 
  max_num_samples: 1000
  with_crowd: True

val_dataloader_params:
  batch_size: 32
  num_workers: 8
  drop_last: False
  pin_memory: True

_convert_: all
```

**Comment by mark1ng123** [comment]
I fixed it, 
i was registering the model not correctly, 
i passed a number of classes parameter to the models.get() method but i didnt modify it with every changing dataset, 
Thanks a lot for pointing me in the right direction @shaydeci
