### ISSUE TITLE
super gradient installation locally doesn't support GPU

### ISSUE THREAD

**Issue by Mohamed2519** [Deci-AI/super-gradients#969]
### Describe the bug
I am facing a problem while I install super gradient locally. It doesn't support GPU.
Here are my steps for installation:
1- create a conda environment with Python 3.10
2-  install the Cuda toolkit and Cudnn with the latest versions
3- pip install super-gradients==3.1.0
 when I check the cuda [ torch.cuda.is_available()] it returns false.
How can I install super gradient that supports cuda

**Comment by BloodAxe** [comment]
SG indeed support GPU.
Most likely there is some error with pytorch installation.
Please use provide the installed environment `pip freeze` and the output of `nvidia-smi` ?
Try re-installting torch manually, that may also help

**Comment by Mohamed2519** [comment]
> 
Thanks for helping. I solved it by installing torch manually. despite it's already installed while installing SG

**Comment by WikiGenius** [comment]
I think the requirements needed to be solved to handle this issue.
to handle the problem of compatibility torch.
